// <auto-generated />
using System;
using CourseScheduling.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseScheduling.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241205185914_MoreClasses")]
    partial class MoreClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseScheduling.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("CurrentEnrollment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Professor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseCode = "CS101",
                            CourseName = "Introduction to Computer Science",
                            Credits = 3,
                            CurrentEnrollment = 2,
                            Description = "Into to Computer Science subjects.",
                            MaxCapacity = 25,
                            Professor = "Prof1",
                            Time = "M/W/F 10:00 AM - 12:00 PM"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseCode = "MATH243",
                            CourseName = "Calculus II",
                            Credits = 4,
                            CurrentEnrollment = 5,
                            Description = "General education math and natural sciences course. Analytic geometry and the calculus in an interrelated form. Students may receive credit for only one of these courses: MATH 144, 242 or 251. This is a Kansas Systemwide Transfer Course.",
                            MaxCapacity = 25,
                            Professor = "Prof2",
                            Time = "T/TR 1:00 PM - 3:00 PM"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseCode = "CS400",
                            CourseName = "Data Structures",
                            Credits = 4,
                            CurrentEnrollment = 2,
                            Description = "Introduces basic data structures and covers their implementations using classes in C++. Includes lists, stacks, queues, binary trees and hash tables.",
                            MaxCapacity = 35,
                            Professor = "Prof3",
                            Time = "T/TR 2:15 PM - 3:30 PM"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseCode = "CS510",
                            CourseName = "Programming Language Concepts",
                            Credits = 3,
                            CurrentEnrollment = 15,
                            Description = "Theoretical concepts in the design and use of programming languages. Formal syntax, including Backus Normal Form (BNF), Extended Backus-Naur Form (EBNF), and syntax diagrams. Semantics, including declaration, allocation and evaluation, symbol table and runtime environment; data types and type checking, procedure activation and parameter passing, modules and abstract data types.",
                            MaxCapacity = 40,
                            Professor = "Prof13",
                            Time = "T/TR 8:30 AM - 9:50 AM"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseCode = "MATH231",
                            CourseName = "Discrete Structures I",
                            Credits = 3,
                            CurrentEnrollment = 25,
                            Description = "A study of some of the basic topics of discrete mathematics, including elementary logic, properties of sets, mathematical induction, counting problems using permutations and combinations, trees, elementary probability, and an introduction to graph theory.",
                            MaxCapacity = 25,
                            Professor = "Prof4",
                            Time = "M/W/F 1:00 PM - 3:00 PM"
                        },
                        new
                        {
                            CourseId = 6,
                            CourseCode = "PSY325",
                            CourseName = "Developmental Psychology",
                            Credits = 3,
                            CurrentEnrollment = 25,
                            Description = "Studies systems of formal logic including sentential and predicate logic. Emphasizes the uses of these systems in the analysis of arguments.",
                            MaxCapacity = 50,
                            Professor = "Prof5",
                            Time = "M/T/F 12:30 PM - 1:45 PM"
                        },
                        new
                        {
                            CourseId = 7,
                            CourseCode = "SOC338",
                            CourseName = "Health & Lifestyle",
                            Credits = 3,
                            CurrentEnrollment = 10,
                            Description = "General education social and behavioral sciences course. Examines the component dimensions of health and the societal-level factors and lifestyle choices that influence health across the life span.",
                            MaxCapacity = 30,
                            Professor = "Prof6",
                            Time = "M/W/F 2:15 PM - 3:30 PM"
                        },
                        new
                        {
                            CourseId = 8,
                            CourseCode = "MKT690J",
                            CourseName = "Social Media Marketing",
                            Credits = 3,
                            CurrentEnrollment = 12,
                            Description = "Social media is an essential part of today’s digital marketing mix and integral to a successful digital strategy. This course provides an introduction to social media marketing and lays the foundation for developing an effective social media campaign. Students learn what social media marketing entails, including the various platforms that exist, selecting the appropriate channels to fit their needs, setting goals and success metrics, and constructing social media strategies that achieve the desired marketing goals. Students also are introduced to quantitative and qualitative measurement tools to evaluate social media initiatives and assess their return on investment for an organization.",
                            MaxCapacity = 20,
                            Professor = "Prof7",
                            Time = "T/TR 9:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 9,
                            CourseCode = "MGMT681",
                            CourseName = "Strategic Management",
                            Credits = 3,
                            CurrentEnrollment = 7,
                            Description = "Choosing and executing the right strategy at the right time in the right way is the most important element of business success. This is a capstone course which integrates the functional areas of business, including management, marketing, finance, accounting and production. Students learn the tools to develop and implement strategies in organizations. Students are challenged through various projects, simulations and case studies to explore domestic and international policy issues, large and small firms, various sources of competitive advantage, and learn to effectively implement a successful strategy. For undergraduate credit only",
                            MaxCapacity = 15,
                            Professor = "Prof8",
                            Time = "M/F/W 3:30 PM - 4:45 PM"
                        },
                        new
                        {
                            CourseId = 10,
                            CourseCode = "NURS362",
                            CourseName = "Clinical Care Lab",
                            Credits = 1,
                            CurrentEnrollment = 0,
                            Description = "Focuses on progression of nursing skills.",
                            MaxCapacity = 25,
                            Professor = "Prof9",
                            Time = "F 1:00 PM - 4:00 PM"
                        },
                        new
                        {
                            CourseId = 11,
                            CourseCode = "GEOG235",
                            CourseName = "Meteorology",
                            Credits = 3,
                            CurrentEnrollment = 25,
                            Description = "General education math and natural sciences course. Cross-listed as GEOL 235. Introductory study of the atmosphere and its properties and the various phenomena of weather. Includes a brief survey of important principles of physical, dynamic, synoptic and applied meteorology. Does not apply toward a major or minor in geology. Requires field trips at the option of the instructor.",
                            MaxCapacity = 40,
                            Professor = "Prof10",
                            Time = "M/W/F 2:15 PM - 3:30 PM"
                        },
                        new
                        {
                            CourseId = 12,
                            CourseCode = "ENGR101",
                            CourseName = "Introduction to Engineering",
                            Credits = 3,
                            CurrentEnrollment = 9,
                            Description = "Assists engineering students in exploring engineering careers and opportunities. Provides information on academic and life skills essential to becoming a successful engineering student. Promotes connections to specific engineering majors and provides activities to assist and reinforce the decision to major in engineering.",
                            MaxCapacity = 15,
                            Professor = "Prof11",
                            Time = "T/TR 11:15 AM - 12:25 PM"
                        },
                        new
                        {
                            CourseId = 13,
                            CourseCode = "CHEM211",
                            CourseName = "General Chemistry I",
                            Credits = 5,
                            CurrentEnrollment = 2,
                            Description = "General education math and natural sciences course. Introduces general concepts of chemistry. Includes chemical stoichiometry, atomic and molecular structure, bonding, gas laws, states of matter and chemical periodicity. CHEM 211-212 meets the needs of students who may wish to take more than one course in chemistry. Credit is allowed in only one of the following: CHEM 211 or 110. Course requires a lab fee. This is a Kansas Systemwide Transfer Course",
                            MaxCapacity = 25,
                            Professor = "Prof12",
                            Time = "T/TR 4:30 PM - 6:00 PM"
                        },
                        new
                        {
                            CourseId = 14,
                            CourseCode = "PHIL125",
                            CourseName = "Introductory Logic",
                            Credits = 3,
                            CurrentEnrollment = 7,
                            Description = "General education humanities course. Introduces students to the use of formal logic as a tool for understanding and evaluating patterns of reasoning. Focuses on deductive validity, logical equivalence and proving soundness. The formal systems introduced in this course are topic-neutral—i.e., they apply to patterns of reasoning on any topic. These formal systems are particularly useful for future studies in areas such as computer science, law, engineering and philosophy.",
                            MaxCapacity = 25,
                            Professor = "Prof13",
                            Time = "M/W/F 10:30 AM - 11:45 AM"
                        },
                        new
                        {
                            CourseId = 15,
                            CourseCode = "PHIL354",
                            CourseName = "Ethics and Computers",
                            Credits = 3,
                            CurrentEnrollment = 5,
                            Description = "General education humanities course. Ethics with application to the ethical issues which may arise from the use of computers, including the moral responsibility of computer professionals for the effect their work has on persons and society; the moral obligations of a computer professional to clients, employer and society; the conceptual and ethical issues surrounding the control and ownership of software; and the justifiability of regulation of the design, use and marketing of computer technology. Course includes diversity content. Prerequisite(s): junior standing or departmental consent.",
                            MaxCapacity = 25,
                            Professor = "Prof14",
                            Time = "M/W/F 9:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 16,
                            CourseCode = "MATH242",
                            CourseName = "Calculus I",
                            Credits = 5,
                            CurrentEnrollment = 17,
                            Description = "General education math and natural sciences course. Analytic geometry and the calculus in an interrelated form. Students may receive credit for only one of these courses: MATH 144, 242 or 251. This is a Kansas Systemwide Transfer Course. Prerequisite(s): MATH 112 with a C or better, or two units of high school algebra, one unit of high school geometry and one-half unit of high school trigonometry, or MATH 123 and 111 with a C or better in each.",
                            MaxCapacity = 35,
                            Professor = "Prof15",
                            Time = "M/W/F 5:45 PM - 7:15 PM"
                        },
                        new
                        {
                            CourseId = 17,
                            CourseCode = "PHYS314",
                            CourseName = "Physics for Scientists II",
                            Credits = 4,
                            CurrentEnrollment = 15,
                            Description = "General education math and natural sciences course. The second semester of a calculus-based physics sequence. Topics include electricity, magnetism, circuits, EM waves, light and selections from modern physics. Credit is only given for one of PHYS 214 or 314. Natural sciences majors are required to take the lab, PHYS 316, that accompanies this course. This is a Kansas Systemwide Transfer Course. Prerequisite(s): MATH 243 with a grade of C or better and PHYS 313.",
                            MaxCapacity = 30,
                            Professor = "Prof16",
                            Time = "M/W/F 4:30 PM - 5:15 PM"
                        },
                        new
                        {
                            CourseId = 18,
                            CourseCode = "PHYS316",
                            CourseName = "University Physics Lab II",
                            Credits = 1,
                            CurrentEnrollment = 15,
                            Description = "General education math and natural sciences course. Lab experiments in electricity, magnetism and optics. Required for natural sciences majors taking PHYS 314. This is a Kansas Systemwide Transfer Course. Pre- or corequisite(s): PHYS 314.",
                            MaxCapacity = 30,
                            Professor = "Prof17",
                            Time = "T/TR 9:30 AM - 12:15 PM"
                        },
                        new
                        {
                            CourseId = 19,
                            CourseCode = "MATH322",
                            CourseName = "Discrete Structures II",
                            Credits = 3,
                            CurrentEnrollment = 21,
                            Description = "Cross-listed as CS 322. Continuation of Discrete Structures I. Includes relations, graphs, trees, Boolean algebra and automata. Prerequisite(s): MATH 321 or CS 321.",
                            MaxCapacity = 25,
                            Professor = "Prof18",
                            Time = "T/TR 9:30 AM - 11:15 AM"
                        },
                        new
                        {
                            CourseId = 20,
                            CourseCode = "PHYS313",
                            CourseName = "Physics for Scientists I",
                            Credits = 4,
                            CurrentEnrollment = 21,
                            Description = "General education math and natural sciences course. The first semester of a calculus-based physics sequence. Topics include motion, forces, energy, fluids, oscillations, waves and thermodynamics. Natural sciences majors are required to take the lab, PHYS 315, that accompanies this course. Credit is given for only one of PHYS 213 or 313. This is a Kansas Systemwide Transfer Course. Pre- or Corequisite(s): MATH 243 with a grade of C or better.",
                            MaxCapacity = 50,
                            Professor = "Prof19",
                            Time = "M/W/F 8:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 21,
                            CourseCode = "IME254",
                            CourseName = "Engineering Probability and Statistics I",
                            Credits = 3,
                            CurrentEnrollment = 57,
                            Description = "Designed for undergraduate students majoring in engineering. It reviews graphical and numerical methods for summarizing and describing datasets, discusses basic concepts of probability, introduces discrete and continuous random variables, and presents statistical methods for making inferences about population parameters. Prerequisite(s): MATH 242.",
                            MaxCapacity = 75,
                            Professor = "Prof20",
                            Time = "M/W/F 8:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 22,
                            CourseCode = "ECE194",
                            CourseName = "Introduction to Digital Design",
                            Credits = 4,
                            CurrentEnrollment = 40,
                            Description = "Introduces digital design concepts. Includes number systems, Boolean algebra, Karnaugh maps, combinational circuit design, adders, multiplexers, decoders, sequential circuit design, state diagram, flip flops, sequence detectors and test different combinational and sequential circuits. Uses CAD tools for circuit simulation. Prerequisite(s): MATH 111 or equivalent. Corequisite(s): ECE 194L.",
                            MaxCapacity = 45,
                            Professor = "Prof22",
                            Time = "T/TR 8:30 AM - 9:45 AM"
                        },
                        new
                        {
                            CourseId = 23,
                            CourseCode = "CS211",
                            CourseName = "Introduction to Programming",
                            Credits = 4,
                            CurrentEnrollment = 40,
                            Description = "First course in computer programming in a high-level language. Emphasizes analyzing problems, designing solutions and expressing them in the form of a well-structured program using the procedural aspects of C++. Prerequisite(s): MATH 111. Corequisite(s): CS 211L.",
                            MaxCapacity = 50,
                            Professor = "Prof23",
                            Time = "T/TR 12:30 PM - 1:45 PM"
                        },
                        new
                        {
                            CourseId = 24,
                            CourseCode = "ECE238",
                            CourseName = "Assesmbly Language Programming for Engineering",
                            Credits = 3,
                            CurrentEnrollment = 27,
                            Description = "Introduces basic concepts of computer organization and operation. Studies machine and assembly language programming concepts that illustrate basic principles and techniques. Laboratory exercises given for experience using personal computers. Prerequisite(s): CS 211.",
                            MaxCapacity = 50,
                            Professor = "Prof24",
                            Time = "T/TR 1:30 PM - 2:45 PM"
                        },
                        new
                        {
                            CourseId = 25,
                            CourseCode = "CS311",
                            CourseName = "Object-Oriented Programming",
                            Credits = 4,
                            CurrentEnrollment = 27,
                            Description = "Concepts of object-oriented programming. Covers data abstractions, classes and objects, methods, inheritance, polymorphism, dynamically-bound method calls and data encapsulation. Includes programming assignments in C++. Prerequisite(s): CS 211. Corequisite(s): CS 311L.",
                            MaxCapacity = 30,
                            Professor = "Prof25",
                            Time = "T/TR 3:30 PM - 5:30 PM"
                        },
                        new
                        {
                            CourseId = 26,
                            CourseCode = "ECE394",
                            CourseName = "Introduction to Computer Architecture",
                            Credits = 3,
                            CurrentEnrollment = 27,
                            Description = "Introduces multilevel approach to computer systems, with an emphasis on micro architecture and instruction set architecture levels. Also introduces techniques to improve performance such as cache memory and instruction level parallelism. Prerequisite(s): ECE 194 and CS 211.",
                            MaxCapacity = 45,
                            Professor = "Prof26",
                            Time = "T/TR 8:30 AM - 9:55 AM"
                        },
                        new
                        {
                            CourseId = 27,
                            CourseCode = "CS410",
                            CourseName = "Programming Paradigms",
                            Credits = 3,
                            CurrentEnrollment = 17,
                            Description = "Overview of different programming paradigms, including their philosophies, uses and relative advantages/disadvantages. Covers the procedural/imperative, functional, logic and object-oriented paradigms. Includes programming assignments in the functional and logic paradigms. Prerequisite(s): CS 311.",
                            MaxCapacity = 50,
                            Professor = "Prof27",
                            Time = "T/TR 9:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 28,
                            CourseCode = "CS664",
                            CourseName = "Computer Networks",
                            Credits = 3,
                            CurrentEnrollment = 10,
                            Description = "Introductory course on computer networking. Introduces concepts and protocols in various network layers with emphasis on the internet. Topics covered include: physical layer (wired and wireless), medium access control and data link layers, packet switching and routing (IP), routing protocols, transport layer (TCP, UDP), congestion and flow control, basic network security, and network applications. Prerequisite(s): undergraduate students: IME 254 and CS 311; graduate students: object oriented programming and statistics/probability knowledge.",
                            MaxCapacity = 50,
                            Professor = "Prof28",
                            Time = "T/TR 4:45 PM - 5:45 PM"
                        },
                        new
                        {
                            CourseId = 29,
                            CourseCode = "CS580",
                            CourseName = "Introduction to Software Engineering",
                            Credits = 3,
                            CurrentEnrollment = 23,
                            Description = "Introduces the processes, methods and tools used in software development and maintenance. Topics include software development life cycle and processes, configuration management, requirements gathering, OOA/D with UML, cohesion and coupling, and unit testing. Prerequisite(s): CS 311.",
                            MaxCapacity = 50,
                            Professor = "Prof29",
                            Time = "T/TR 10:45 AM - 12:05 PM"
                        },
                        new
                        {
                            CourseId = 30,
                            CourseCode = "CS540",
                            CourseName = "Operating Systems",
                            Credits = 3,
                            CurrentEnrollment = 45,
                            Description = "Fundamental principles of modern operating systems. CPU management including processes, threads, scheduling, synchronization, resource allocation and deadlocks. Memory management including paging and virtual memory. Storage management and file systems. Prerequisite(s): ECE 238 and CS 311.",
                            MaxCapacity = 50,
                            Professor = "Prof30",
                            Time = "T/TR 10:45 AM - 12:15 PM"
                        },
                        new
                        {
                            CourseId = 31,
                            CourseCode = "CS560",
                            CourseName = "Design and Analysis of Algorithms",
                            Credits = 3,
                            CurrentEnrollment = 17,
                            Description = "Design of various algorithms including several sorting algorithms. Analysis of their space and time complexities. Data structures include heaps, hash tables and binary search trees. Prerequisite(s): CS 322, 400; STAT 460 or IME 254.",
                            MaxCapacity = 25,
                            Professor = "Prof31",
                            Time = "T/TR 12:30 PM - 1:45 PM"
                        },
                        new
                        {
                            CourseId = 32,
                            CourseCode = "CS665",
                            CourseName = "Introduction to Database Systems",
                            Credits = 3,
                            CurrentEnrollment = 53,
                            Description = "Fundamental aspects of relational database systems, conceptual database design and entity-relationship modeling; the relational data model and its foundations, relational languages and SQL, functional dependencies and logical database design; views, constraints and triggers. Course includes a group project involving the design and implementation of a relational database and embedded SQL programming. Prerequisite(s): CS 311, MATH 322.",
                            MaxCapacity = 75,
                            Professor = "Prof32",
                            Time = "T/TR 5:30 PM - 6:45 PM"
                        },
                        new
                        {
                            CourseId = 33,
                            CourseCode = "CS356",
                            CourseName = "Introduction to Computer Security",
                            Credits = 3,
                            CurrentEnrollment = 43,
                            Description = "Provides a first approach to the security mindset. Covers how adversaries exploit common software vulnerabilities such as buffer overflows and race conditions. Students learn secure coding techniques and countermeasures. Topics also include cryptography principles, web security, and legal and ethical aspects. Prerequisite(s): CS 211.",
                            MaxCapacity = 50,
                            Professor = "Prof33",
                            Time = "M/W 2:00 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 34,
                            CourseCode = "CS598",
                            CourseName = "Senior Design Project I",
                            Credits = 2,
                            CurrentEnrollment = 43,
                            Description = "Cross-listed as ECE 585. Design project under faculty supervision chosen according to the student's interest. Does not count toward a graduate degree in electrical engineering, computer engineering or computer science. This class should be taken in the semester prior to the one in which the student is going to graduate. For undergraduate credit only. Prerequisite(s): senior standing, ECE 492 or CS 580. Pre- or corequisite(s): PHIL 354 or PHIL 385.",
                            MaxCapacity = 75,
                            Professor = "Prof34",
                            Time = "F 9:30 AM - 12:15 PM"
                        },
                        new
                        {
                            CourseId = 35,
                            CourseCode = "CS599",
                            CourseName = "Senior Design Project II",
                            Credits = 2,
                            CurrentEnrollment = 43,
                            Description = "This is the second part of a sequence of two courses (CS 598 and CS 599) that have to be taken in two consecutive semesters. Students failing this course must retake the CS 598 course. For undergraduate credit only. Prerequisite(s): CS 598. Pre- or corequisite(s): PHYS 314 and PHYS 316.",
                            MaxCapacity = 75,
                            Professor = "Prof35",
                            Time = "F 2:00 PM - 5:45 PM"
                        },
                        new
                        {
                            CourseId = 36,
                            CourseCode = "MATH511",
                            CourseName = "Linear Algebra",
                            Credits = 3,
                            CurrentEnrollment = 30,
                            Description = "An elementary study of linear algebra, including an examination of linear transformations and matrices over finite dimensional spaces. Prerequisite(s): MATH 243 with a grade point of 2.000 or better.",
                            MaxCapacity = 35,
                            Professor = "Prof36",
                            Time = "M/W/F 1:45 PM - 3:15 PM"
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2024, 12, 5, 12, 59, 13, 575, DateTimeKind.Local).AddTicks(1183),
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "test@student.com",
                            FirstName = "Test Student",
                            LastName = "Onetest Student",
                            Major = "Computer Science",
                            Password = "test123",
                            Year = "Sophomore"
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentCourseId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("CourseScheduling.Models.Waitlist", b =>
                {
                    b.Property<int>("WaitlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaitlistId"));

                    b.Property<DateTime>("AddedToWaitlist")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("WaitlistId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Waitlists");
                });

            modelBuilder.Entity("CourseScheduling.Models.Enrollment", b =>
                {
                    b.HasOne("CourseScheduling.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseScheduling.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseScheduling.Models.StudentCourse", b =>
                {
                    b.HasOne("CourseScheduling.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseScheduling.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseScheduling.Models.Waitlist", b =>
                {
                    b.HasOne("CourseScheduling.Models.Course", "Course")
                        .WithMany("Waitlists")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseScheduling.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseScheduling.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("CourseScheduling.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
