// <auto-generated />
using System;
using CourseScheduling.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseScheduling.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseScheduling.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("CurrentEnrollment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Professor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseCode = "CS101",
                            CourseName = "Introduction to Computer Science",
                            Credits = 3,
                            CurrentEnrollment = 2,
                            Description = "Into to Computer Science subjects.",
                            MaxCapacity = 25,
                            Professor = "Prof1",
                            Time = "M/W/F 10:00 AM - 12:00 PM"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseCode = "MATH243",
                            CourseName = "Calculus II",
                            Credits = 4,
                            CurrentEnrollment = 5,
                            Description = "General education math and natural sciences course. Analytic geometry and the calculus in an interrelated form. Students may receive credit for only one of these courses: MATH 144, 242 or 251. This is a Kansas Systemwide Transfer Course.",
                            MaxCapacity = 25,
                            Professor = "Prof2",
                            Time = "T/TR 1:00 PM - 3:00 PM"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseCode = "CS400",
                            CourseName = "Data Structures",
                            Credits = 4,
                            CurrentEnrollment = 2,
                            Description = "Introduces basic data structures and covers their implementations using classes in C++. Includes lists, stacks, queues, binary trees and hash tables.",
                            MaxCapacity = 35,
                            Professor = "Prof3",
                            Time = "T/TR 2:15 PM - 3:30 PM"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseCode = "CS510",
                            CourseName = "Programming Language Concepts",
                            Credits = 3,
                            CurrentEnrollment = 15,
                            Description = "Theoretical concepts in the design and use of programming languages. Formal syntax, including Backus Normal Form (BNF), Extended Backus-Naur Form (EBNF), and syntax diagrams. Semantics, including declaration, allocation and evaluation, symbol table and runtime environment; data types and type checking, procedure activation and parameter passing, modules and abstract data types.",
                            MaxCapacity = 40,
                            Professor = "Prof13",
                            Time = "T/TR 8:30 AM - 9:50 AM"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseCode = "MATH321",
                            CourseName = "Discrete Structures I",
                            Credits = 3,
                            CurrentEnrollment = 25,
                            Description = "A study of some of the basic topics of discrete mathematics, including elementary logic, properties of sets, mathematical induction, counting problems using permutations and combinations, trees, elementary probability, and an introduction to graph theory.",
                            MaxCapacity = 25,
                            Professor = "Prof4",
                            Time = "M/W/F 1:00 PM - 3:00 PM"
                        },
                        new
                        {
                            CourseId = 6,
                            CourseCode = "PSY325",
                            CourseName = "Developmental Psychology",
                            Credits = 3,
                            CurrentEnrollment = 25,
                            Description = "Studies systems of formal logic including sentential and predicate logic. Emphasizes the uses of these systems in the analysis of arguments.",
                            MaxCapacity = 50,
                            Professor = "Prof5",
                            Time = "M/T/F 12:30 PM - 1:45 PM"
                        },
                        new
                        {
                            CourseId = 7,
                            CourseCode = "SOC338",
                            CourseName = "Health & Lifestyle",
                            Credits = 3,
                            CurrentEnrollment = 10,
                            Description = "General education social and behavioral sciences course. Examines the component dimensions of health and the societal-level factors and lifestyle choices that influence health across the life span.",
                            MaxCapacity = 30,
                            Professor = "Prof6",
                            Time = "M/W/F 2:15 PM - 3:30 PM"
                        },
                        new
                        {
                            CourseId = 8,
                            CourseCode = "MKT690J",
                            CourseName = "Social Media Marketing",
                            Credits = 3,
                            CurrentEnrollment = 12,
                            Description = "Social media is an essential part of today’s digital marketing mix and integral to a successful digital strategy. This course provides an introduction to social media marketing and lays the foundation for developing an effective social media campaign. Students learn what social media marketing entails, including the various platforms that exist, selecting the appropriate channels to fit their needs, setting goals and success metrics, and constructing social media strategies that achieve the desired marketing goals. Students also are introduced to quantitative and qualitative measurement tools to evaluate social media initiatives and assess their return on investment for an organization.",
                            MaxCapacity = 20,
                            Professor = "Prof7",
                            Time = "T/TR 9:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 9,
                            CourseCode = "MGMT681",
                            CourseName = "Strategic Management",
                            Credits = 3,
                            CurrentEnrollment = 7,
                            Description = "Choosing and executing the right strategy at the right time in the right way is the most important element of business success. This is a capstone course which integrates the functional areas of business, including management, marketing, finance, accounting and production. Students learn the tools to develop and implement strategies in organizations. Students are challenged through various projects, simulations and case studies to explore domestic and international policy issues, large and small firms, various sources of competitive advantage, and learn to effectively implement a successful strategy. For undergraduate credit only",
                            MaxCapacity = 15,
                            Professor = "Prof8",
                            Time = "M/F/W 3:30 PM - 4:45 PM"
                        },
                        new
                        {
                            CourseId = 10,
                            CourseCode = "NURS362",
                            CourseName = "Clinical Care Lab",
                            Credits = 1,
                            CurrentEnrollment = 0,
                            Description = "Focuses on progression of nursing skills.",
                            MaxCapacity = 25,
                            Professor = "Prof9",
                            Time = "F 1:00 PM - 4:00 PM"
                        },
                        new
                        {
                            CourseId = 11,
                            CourseCode = "GEOG235",
                            CourseName = "Meteorology",
                            Credits = 3,
                            CurrentEnrollment = 25,
                            Description = "General education math and natural sciences course. Cross-listed as GEOL 235. Introductory study of the atmosphere and its properties and the various phenomena of weather. Includes a brief survey of important principles of physical, dynamic, synoptic and applied meteorology. Does not apply toward a major or minor in geology. Requires field trips at the option of the instructor.",
                            MaxCapacity = 40,
                            Professor = "Prof10",
                            Time = "M/W/F 2:15 PM - 3:30 PM"
                        },
                        new
                        {
                            CourseId = 12,
                            CourseCode = "ENGR101",
                            CourseName = "Introduction to Engineering",
                            Credits = 3,
                            CurrentEnrollment = 9,
                            Description = "Assists engineering students in exploring engineering careers and opportunities. Provides information on academic and life skills essential to becoming a successful engineering student. Promotes connections to specific engineering majors and provides activities to assist and reinforce the decision to major in engineering.",
                            MaxCapacity = 15,
                            Professor = "Prof11",
                            Time = "T/TR 11:15 AM - 12:25 PM"
                        },
                        new
                        {
                            CourseId = 13,
                            CourseCode = "CHEM211",
                            CourseName = "General Chemistry I",
                            Credits = 5,
                            CurrentEnrollment = 2,
                            Description = "General education math and natural sciences course. Introduces general concepts of chemistry. Includes chemical stoichiometry, atomic and molecular structure, bonding, gas laws, states of matter and chemical periodicity. CHEM 211-212 meets the needs of students who may wish to take more than one course in chemistry. Credit is allowed in only one of the following: CHEM 211 or 110. Course requires a lab fee. This is a Kansas Systemwide Transfer Course",
                            MaxCapacity = 25,
                            Professor = "Prof12",
                            Time = "T/TR 4:30 PM - 6:00 PM"
                        },
                        new
                        {
                            CourseId = 14,
                            CourseCode = "PHIL125",
                            CourseName = "Introductory Logic",
                            Credits = 3,
                            CurrentEnrollment = 7,
                            Description = "General education humanities course. Introduces students to the use of formal logic as a tool for understanding and evaluating patterns of reasoning. Focuses on deductive validity, logical equivalence and proving soundness. The formal systems introduced in this course are topic-neutral—i.e., they apply to patterns of reasoning on any topic. These formal systems are particularly useful for future studies in areas such as computer science, law, engineering and philosophy.",
                            MaxCapacity = 25,
                            Professor = "Prof13",
                            Time = "M/W/F 10:30 AM - 11:45 AM"
                        },
                        new
                        {
                            CourseId = 15,
                            CourseCode = "PHIL354",
                            CourseName = "Ethics and Computers",
                            Credits = 3,
                            CurrentEnrollment = 5,
                            Description = "General education humanities course. Ethics with application to the ethical issues which may arise from the use of computers, including the moral responsibility of computer professionals for the effect their work has on persons and society; the moral obligations of a computer professional to clients, employer and society; the conceptual and ethical issues surrounding the control and ownership of software; and the justifiability of regulation of the design, use and marketing of computer technology. Course includes diversity content. Prerequisite(s): junior standing or departmental consent.",
                            MaxCapacity = 25,
                            Professor = "Prof14",
                            Time = "M/W/F 9:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 16,
                            CourseCode = "MATH242",
                            CourseName = "Calculus I",
                            Credits = 5,
                            CurrentEnrollment = 17,
                            Description = "General education math and natural sciences course. Analytic geometry and the calculus in an interrelated form. Students may receive credit for only one of these courses: MATH 144, 242 or 251. This is a Kansas Systemwide Transfer Course. Prerequisite(s): MATH 112 with a C or better, or two units of high school algebra, one unit of high school geometry and one-half unit of high school trigonometry, or MATH 123 and 111 with a C or better in each.",
                            MaxCapacity = 35,
                            Professor = "Prof15",
                            Time = "M/W/F 5:45 PM - 7:15 PM"
                        },
                        new
                        {
                            CourseId = 17,
                            CourseCode = "PHYS314",
                            CourseName = "Physics for Scientists II",
                            Credits = 4,
                            CurrentEnrollment = 15,
                            Description = "General education math and natural sciences course. The second semester of a calculus-based physics sequence. Topics include electricity, magnetism, circuits, EM waves, light and selections from modern physics. Credit is only given for one of PHYS 214 or 314. Natural sciences majors are required to take the lab, PHYS 316, that accompanies this course. This is a Kansas Systemwide Transfer Course. Prerequisite(s): MATH 243 with a grade of C or better and PHYS 313.",
                            MaxCapacity = 30,
                            Professor = "Prof16",
                            Time = "M/W/F 4:30 PM - 5:15 PM"
                        },
                        new
                        {
                            CourseId = 18,
                            CourseCode = "PHYS316",
                            CourseName = "University Physics Lab II",
                            Credits = 1,
                            CurrentEnrollment = 15,
                            Description = "General education math and natural sciences course. Lab experiments in electricity, magnetism and optics. Required for natural sciences majors taking PHYS 314. This is a Kansas Systemwide Transfer Course. Pre- or corequisite(s): PHYS 314.",
                            MaxCapacity = 30,
                            Professor = "Prof17",
                            Time = "T/TR 9:30 AM - 12:15 PM"
                        },
                        new
                        {
                            CourseId = 19,
                            CourseCode = "MATH322",
                            CourseName = "Discrete Structures II",
                            Credits = 3,
                            CurrentEnrollment = 21,
                            Description = "Cross-listed as CS 322. Continuation of Discrete Structures I. Includes relations, graphs, trees, Boolean algebra and automata. Prerequisite(s): MATH 321 or CS 321.",
                            MaxCapacity = 25,
                            Professor = "Prof18",
                            Time = "T/TR 9:30 AM - 11:15 AM"
                        },
                        new
                        {
                            CourseId = 20,
                            CourseCode = "PHYS313",
                            CourseName = "Physics for Scientists I",
                            Credits = 4,
                            CurrentEnrollment = 21,
                            Description = "General education math and natural sciences course. The first semester of a calculus-based physics sequence. Topics include motion, forces, energy, fluids, oscillations, waves and thermodynamics. Natural sciences majors are required to take the lab, PHYS 315, that accompanies this course. Credit is given for only one of PHYS 213 or 313. This is a Kansas Systemwide Transfer Course. Pre- or Corequisite(s): MATH 243 with a grade of C or better.",
                            MaxCapacity = 50,
                            Professor = "Prof19",
                            Time = "M/W/F 8:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 21,
                            CourseCode = "IME254",
                            CourseName = "Engineering Probability and Statistics I",
                            Credits = 3,
                            CurrentEnrollment = 57,
                            Description = "Designed for undergraduate students majoring in engineering. It reviews graphical and numerical methods for summarizing and describing datasets, discusses basic concepts of probability, introduces discrete and continuous random variables, and presents statistical methods for making inferences about population parameters. Prerequisite(s): MATH 242.",
                            MaxCapacity = 75,
                            Professor = "Prof20",
                            Time = "M/W/F 8:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 22,
                            CourseCode = "ECE194",
                            CourseName = "Introduction to Digital Design",
                            Credits = 4,
                            CurrentEnrollment = 40,
                            Description = "Introduces digital design concepts. Includes number systems, Boolean algebra, Karnaugh maps, combinational circuit design, adders, multiplexers, decoders, sequential circuit design, state diagram, flip flops, sequence detectors and test different combinational and sequential circuits. Uses CAD tools for circuit simulation. Prerequisite(s): MATH 111 or equivalent. Corequisite(s): ECE 194L.",
                            MaxCapacity = 45,
                            Professor = "Prof22",
                            Time = "T/TR 8:30 AM - 9:45 AM"
                        },
                        new
                        {
                            CourseId = 23,
                            CourseCode = "CS211",
                            CourseName = "Introduction to Programming",
                            Credits = 4,
                            CurrentEnrollment = 40,
                            Description = "First course in computer programming in a high-level language. Emphasizes analyzing problems, designing solutions and expressing them in the form of a well-structured program using the procedural aspects of C++. Prerequisite(s): MATH 111. Corequisite(s): CS 211L.",
                            MaxCapacity = 50,
                            Professor = "Prof23",
                            Time = "T/TR 12:30 PM - 1:45 PM"
                        },
                        new
                        {
                            CourseId = 24,
                            CourseCode = "ECE238",
                            CourseName = "Assesmbly Language Programming for Engineering",
                            Credits = 3,
                            CurrentEnrollment = 27,
                            Description = "Introduces basic concepts of computer organization and operation. Studies machine and assembly language programming concepts that illustrate basic principles and techniques. Laboratory exercises given for experience using personal computers. Prerequisite(s): CS 211.",
                            MaxCapacity = 50,
                            Professor = "Prof24",
                            Time = "T/TR 1:30 PM - 2:45 PM"
                        },
                        new
                        {
                            CourseId = 25,
                            CourseCode = "CS311",
                            CourseName = "Object-Oriented Programming",
                            Credits = 4,
                            CurrentEnrollment = 27,
                            Description = "Concepts of object-oriented programming. Covers data abstractions, classes and objects, methods, inheritance, polymorphism, dynamically-bound method calls and data encapsulation. Includes programming assignments in C++. Prerequisite(s): CS 211. Corequisite(s): CS 311L.",
                            MaxCapacity = 30,
                            Professor = "Prof25",
                            Time = "T/TR 3:30 PM - 5:30 PM"
                        },
                        new
                        {
                            CourseId = 26,
                            CourseCode = "ECE394",
                            CourseName = "Introduction to Computer Architecture",
                            Credits = 3,
                            CurrentEnrollment = 27,
                            Description = "Introduces multilevel approach to computer systems, with an emphasis on micro architecture and instruction set architecture levels. Also introduces techniques to improve performance such as cache memory and instruction level parallelism. Prerequisite(s): ECE 194 and CS 211.",
                            MaxCapacity = 45,
                            Professor = "Prof26",
                            Time = "T/TR 8:30 AM - 9:55 AM"
                        },
                        new
                        {
                            CourseId = 27,
                            CourseCode = "CS410",
                            CourseName = "Programming Paradigms",
                            Credits = 3,
                            CurrentEnrollment = 17,
                            Description = "Overview of different programming paradigms, including their philosophies, uses and relative advantages/disadvantages. Covers the procedural/imperative, functional, logic and object-oriented paradigms. Includes programming assignments in the functional and logic paradigms. Prerequisite(s): CS 311.",
                            MaxCapacity = 50,
                            Professor = "Prof27",
                            Time = "T/TR 9:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 28,
                            CourseCode = "CS664",
                            CourseName = "Computer Networks",
                            Credits = 3,
                            CurrentEnrollment = 10,
                            Description = "Introductory course on computer networking. Introduces concepts and protocols in various network layers with emphasis on the internet. Topics covered include: physical layer (wired and wireless), medium access control and data link layers, packet switching and routing (IP), routing protocols, transport layer (TCP, UDP), congestion and flow control, basic network security, and network applications. Prerequisite(s): undergraduate students: IME 254 and CS 311; graduate students: object oriented programming and statistics/probability knowledge.",
                            MaxCapacity = 50,
                            Professor = "Prof28",
                            Time = "T/TR 4:45 PM - 5:45 PM"
                        },
                        new
                        {
                            CourseId = 29,
                            CourseCode = "CS580",
                            CourseName = "Introduction to Software Engineering",
                            Credits = 3,
                            CurrentEnrollment = 23,
                            Description = "Introduces the processes, methods and tools used in software development and maintenance. Topics include software development life cycle and processes, configuration management, requirements gathering, OOA/D with UML, cohesion and coupling, and unit testing. Prerequisite(s): CS 311.",
                            MaxCapacity = 50,
                            Professor = "Prof29",
                            Time = "T/TR 10:45 AM - 12:05 PM"
                        },
                        new
                        {
                            CourseId = 30,
                            CourseCode = "CS540",
                            CourseName = "Operating Systems",
                            Credits = 3,
                            CurrentEnrollment = 45,
                            Description = "Fundamental principles of modern operating systems. CPU management including processes, threads, scheduling, synchronization, resource allocation and deadlocks. Memory management including paging and virtual memory. Storage management and file systems. Prerequisite(s): ECE 238 and CS 311.",
                            MaxCapacity = 50,
                            Professor = "Prof30",
                            Time = "T/TR 10:45 AM - 12:15 PM"
                        },
                        new
                        {
                            CourseId = 31,
                            CourseCode = "CS560",
                            CourseName = "Design and Analysis of Algorithms",
                            Credits = 3,
                            CurrentEnrollment = 17,
                            Description = "Design of various algorithms including several sorting algorithms. Analysis of their space and time complexities. Data structures include heaps, hash tables and binary search trees. Prerequisite(s): CS 322, 400; STAT 460 or IME 254.",
                            MaxCapacity = 25,
                            Professor = "Prof31",
                            Time = "T/TR 12:30 PM - 1:45 PM"
                        },
                        new
                        {
                            CourseId = 32,
                            CourseCode = "CS665",
                            CourseName = "Introduction to Database Systems",
                            Credits = 3,
                            CurrentEnrollment = 53,
                            Description = "Fundamental aspects of relational database systems, conceptual database design and entity-relationship modeling; the relational data model and its foundations, relational languages and SQL, functional dependencies and logical database design; views, constraints and triggers. Course includes a group project involving the design and implementation of a relational database and embedded SQL programming. Prerequisite(s): CS 311, MATH 322.",
                            MaxCapacity = 75,
                            Professor = "Prof32",
                            Time = "T/TR 5:30 PM - 6:45 PM"
                        },
                        new
                        {
                            CourseId = 33,
                            CourseCode = "CS356",
                            CourseName = "Introduction to Computer Security",
                            Credits = 3,
                            CurrentEnrollment = 43,
                            Description = "Provides a first approach to the security mindset. Covers how adversaries exploit common software vulnerabilities such as buffer overflows and race conditions. Students learn secure coding techniques and countermeasures. Topics also include cryptography principles, web security, and legal and ethical aspects. Prerequisite(s): CS 211.",
                            MaxCapacity = 50,
                            Professor = "Prof33",
                            Time = "M/W 2:00 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 34,
                            CourseCode = "CS598",
                            CourseName = "Senior Design Project I",
                            Credits = 2,
                            CurrentEnrollment = 43,
                            Description = "Cross-listed as ECE 585. Design project under faculty supervision chosen according to the student's interest. Does not count toward a graduate degree in electrical engineering, computer engineering or computer science. This class should be taken in the semester prior to the one in which the student is going to graduate. For undergraduate credit only. Prerequisite(s): senior standing, ECE 492 or CS 580. Pre- or corequisite(s): PHIL 354 or PHIL 385.",
                            MaxCapacity = 75,
                            Professor = "Prof34",
                            Time = "F 9:30 AM - 12:15 PM"
                        },
                        new
                        {
                            CourseId = 35,
                            CourseCode = "CS599",
                            CourseName = "Senior Design Project II",
                            Credits = 2,
                            CurrentEnrollment = 43,
                            Description = "This is the second part of a sequence of two courses (CS 598 and CS 599) that have to be taken in two consecutive semesters. Students failing this course must retake the CS 598 course. For undergraduate credit only. Prerequisite(s): CS 598. Pre- or corequisite(s): PHYS 314 and PHYS 316.",
                            MaxCapacity = 75,
                            Professor = "Prof35",
                            Time = "F 2:00 PM - 5:45 PM"
                        },
                        new
                        {
                            CourseId = 36,
                            CourseCode = "PSY111",
                            CourseName = "General Psychology",
                            Credits = 3,
                            CurrentEnrollment = 45,
                            Description = "General education social and behavioral sciences course. Introduces the general principles and areas of psychology. Includes learning, perceiving, thinking, behavioral development, intelligence, personality and abnormalities of behavior. Course is a prerequisite for advanced and specialized courses in psychology. This is a Kansas Systemwide Transfer Course.",
                            MaxCapacity = 50,
                            Professor = "Prof37",
                            Time = "M/W/F 1:45 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 37,
                            CourseCode = "ECON201",
                            CourseName = "Principles of Macroeconomics",
                            Credits = 3,
                            CurrentEnrollment = 30,
                            Description = "General education social and behavioral sciences course. Introduces economic concepts of scarcity, markets and prices. Emphasizes business cycles, recessions and recoveries, unemployment, inflation, monetary and fiscal policy. Discusses money and the banking system, the Federal Reserve, and trade and the impact of the global economy. This is a Kansas Systemwide Transfer Course.",
                            MaxCapacity = 45,
                            Professor = "Prof38",
                            Time = "T/TR 1:45 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 38,
                            CourseCode = "MATH123",
                            CourseName = "College Trigonometry",
                            Credits = 3,
                            CurrentEnrollment = 4,
                            Description = "Studies the trigonometric functions and their applications. Credit in both MATH 123 and 112 is not allowed. This is a Kansas Systemwide Transfer Course. Prerequisite(s): MATH 111 with C or better or equivalent high school preparation and one unit of high school geometry.",
                            MaxCapacity = 30,
                            Professor = "Prof39",
                            Time = "M/W/F 12:30 PM - 1:55 PM"
                        },
                        new
                        {
                            CourseId = 39,
                            CourseCode = "PSY323",
                            CourseName = "Social Psychology",
                            Credits = 3,
                            CurrentEnrollment = 8,
                            Description = "General education social and behavioral sciences course. Studies perception of self, others and groups. Includes attitude formation and change, group processes like conformity, compliance and conflict, and interpersonal processes such as attraction and the formation of close relationships. Also includes the application of social psychological principles to the study of prosocial and aggressive behavior. Prerequisite(s): PSY 111.",
                            MaxCapacity = 30,
                            Professor = "Prof40",
                            Time = "M/W/F 9:30 AM - 10:45 AM"
                        },
                        new
                        {
                            CourseId = 40,
                            CourseCode = "PSY405",
                            CourseName = "Human Factors Psychology",
                            Credits = 3,
                            CurrentEnrollment = 30,
                            Description = "The study of how people respond to the demands of complex machines and the varied environments of workplace, home and other settings. Introduces the tools and methods of machine, task and environment design to achieve the matching of human capabilities and the demands of machines and environments so as to enhance human performance and well being. Prerequisite(s): PSY 111.",
                            MaxCapacity = 45,
                            Professor = "Prof41",
                            Time = "T/TH 9:45 AM - 11:00 AM"
                        },
                        new
                        {
                            CourseId = 41,
                            CourseCode = "STAT370",
                            CourseName = "Elementary Statistics",
                            Credits = 3,
                            CurrentEnrollment = 17,
                            Description = "General education math and natural sciences course. Surveys elementary descriptive statistics, binomial and normal distributions, elementary problems of statistical inference, linear correlation and regression. Not open to mathematics majors. Students cannot receive credit for both STAT 171 and STAT 370. This is a Kansas Systemwide Transfer Course. Prerequisite(s): MATH 111 with a C or better or equivalent.",
                            MaxCapacity = 30,
                            Professor = "Prof42",
                            Time = "M/W/F 1:45 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 42,
                            CourseCode = "AC121",
                            CourseName = "Cybersecurity Awareness",
                            Credits = 3,
                            CurrentEnrollment = 30,
                            Description = "The ability to secure information and systems within a modern enterprise in this modern globalized environment is a growing challenge. Ever-present human threats are global, persistent and increasingly sophisticated. Natural threats are unpredictable but inevitable. Vulnerabilities within the complex and interdependent system of systems continue to be discovered with many more yet to become common knowledge. Exploited vulnerabilities can have a devastating impact on an organization or even a society. This course is designed to familiarize users with information, cyberspace and security principles needed to understand these threats. To this end, the course addresses a range of topics, including information infrastructures, social engineering, information system exploitation techniques and countermeasures to the threats discussed. Pre- or corequisite(s): PHIL 125 or PHIL 105.",
                            MaxCapacity = 30,
                            Professor = "Prof43",
                            Time = "T/TR 8:30 AM - 10:00 AM"
                        },
                        new
                        {
                            CourseId = 43,
                            CourseCode = "AC201",
                            CourseName = "Introductory Design Project",
                            Credits = 1,
                            CurrentEnrollment = 2,
                            Description = "The first of the three-course project design series. The course introduces students to project design, prototyping, engineering standards and professional reports. Students are part of teams, learn prototyping skills and have hands on experiences in a maker-space. Students learn project management tools, team working tools, how to perform market research and develop videos, and prototype development. Prerequisite(s): FYET 102A, FYET 102B, ENGR 302, ID 300 or instructor's consent.",
                            MaxCapacity = 30,
                            Professor = "Prof44",
                            Time = "M/W/F 4:15 PM - 5:45 PM"
                        },
                        new
                        {
                            CourseId = 44,
                            CourseCode = "AC222",
                            CourseName = "Applied Computing Fundamentals",
                            Credits = 3,
                            CurrentEnrollment = 12,
                            Description = "Information technology (IT) virtually connects people and businesses in the world. The daily operations of every organization in the public and private sector heavily rely on the internet. This course allows students to gain vital concepts on computer hardware, computer systems, networking and security to solve real-world computing challenges. This course is a key for anyone who wants to gain basic skills in the computing sector. Students collaborate effectively and think critically to develop skills in computing and networking. Students learn to use industry-standard tools through hands-on class projects.",
                            MaxCapacity = 30,
                            Professor = "Prof45",
                            Time = "M/W/F 11:45 AM - 1:20 PM"
                        },
                        new
                        {
                            CourseId = 45,
                            CourseCode = "AC301",
                            CourseName = "Junior Project",
                            Credits = 2,
                            CurrentEnrollment = 30,
                            Description = "Second course in four-course project sequence. Introduces students to engineering design concepts with an entrepreneurial mindset. This includes customer discovery and value creation techniques as well as engineering design and project management tools. Prerequisite(s): AC 201 or ENGR 205 or instructor's consent.",
                            MaxCapacity = 50,
                            Professor = "Prof46",
                            Time = "M/W/F 1:45 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 46,
                            CourseCode = "AC321",
                            CourseName = "Applied Networking",
                            Credits = 3,
                            CurrentEnrollment = 22,
                            Description = "Information technology (IT) virtually connects people and businesses in the world. The daily operations of every organization in the public and private sector heavily rely on the internet. This course allows students to gain vital concepts on computer networking and security to solve real-world computing challenges. This course is a key for anyone who wants to gain advanced skills in the computing sector. Students collaborate effectively and think critically to develop skills in computer networking. Students learn to use industry-standard tools through hands-on class projects.",
                            MaxCapacity = 30,
                            Professor = "Prof47",
                            Time = "M/W/F 3:45 PM - 5:15 PM"
                        },
                        new
                        {
                            CourseId = 47,
                            CourseCode = "AC322",
                            CourseName = "Applied Programming and Scripting",
                            Credits = 3,
                            CurrentEnrollment = 21,
                            Description = "Good scripting skills are vital to IT experts in the fields of information security. This course is designed for cybersecurity professionals who are interested in learning basic coding skills to perform the cybersecurity tasks more efficiently. The course assists students in taking their cybersecurity career to the next level by teaching the vital skills needed to develop as well as customize applications that interact with file systems, databases, networks and websites. Covers command shell scripting (cmd, powershell, bash) in Windows and Linux operating systems. Emphasizes scripting cybersecurity tasks such as system configuration, system auditing and penetration testing. Also covers Arduino microcontrollers, coding Arduino in Python and coding TCP Traceroute. Python language is used in this course. Prerequisite(s): AC 222 or MIS 325.",
                            MaxCapacity = 30,
                            Professor = "Prof48",
                            Time = "F 1:45 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 48,
                            CourseCode = "AC324",
                            CourseName = "Applied Web Applications and Database Development",
                            Credits = 3,
                            CurrentEnrollment = 14,
                            Description = "When browsing on a web application, look for two things: how user-friendly the web app is and how the information is stored, controlled and used. Each web application has a set of requirements such as financial transaction, customer information, etc. The course covers web and database technologies, services, protocols, design and operation. Students learn a variety of languages including HTML, CSS, Apache and MySQL. Course is designed to apply the languages through hands-on projects. Prerequisite(s): AC 222 or MIS 325 or CS 664. Pre- or corequisite(s): ECON 201 or IME 255.",
                            MaxCapacity = 30,
                            Professor = "Prof49",
                            Time = "F 12:45 PM - 2:15 PM"
                        },
                        new
                        {
                            CourseId = 49,
                            CourseCode = "AC326",
                            CourseName = "Cyber Operations",
                            Credits = 3,
                            CurrentEnrollment = 1,
                            Description = "Covers concepts related to cyber attack, penetration testing, cyber intelligence, cryptography and cyber defense. Students learn the attacker's perspective and how security infrastructure integrates with the rest of the business and IT infrastructure through the use of hands-on projects. Prerequisite(s): AC 121, AC 222, AC 321 and AC 322 .",
                            MaxCapacity = 30,
                            Professor = "Prof50",
                            Time = "M/W/F 1:45 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 50,
                            CourseCode = "AC352",
                            CourseName = "Competitive Ethical Hacking",
                            Credits = 3,
                            CurrentEnrollment = 9,
                            Description = "Kevin Mitnick, who popularized the term “social engineering,” explained that it is much easier to trick someone into revealing a password for a system than to exert the effort of hacking into the system. Mitnick claims that this social engineering tactic was the single-most effective method in his arsenal. This course covers human threats to cybersecurity in political, social and economic contexts. It includes targeted exploitation/manipulation of individuals, small groups and larger groups through social engineering, marketing, propaganda, psychological operations by personal contact, email, social networking, web and RF transmission. Prerequisite(s): AC 121 .",
                            MaxCapacity = 25,
                            Professor = "Prof51",
                            Time = "M/W/F 1:45 PM - 3:15 PM"
                        },
                        new
                        {
                            CourseId = 51,
                            CourseCode = "AC363",
                            CourseName = "Human Threats to Cybersecurity",
                            Credits = 3,
                            CurrentEnrollment = 9,
                            Description = "Cross-listed as CS 352. Presents fundamental concepts of competitive ethical hacking in computer and network security. The course introduces the command line interface, open-source intelligence, cryptography, digital forensics, web application security, software reverse engineering, secure programming and log analysis. Assignments include participating in capture the flag competitions. Prerequisite(s): CS 211 or (AC 121 and AC 322).",
                            MaxCapacity = 30,
                            Professor = "Prof52",
                            Time = "T/TR 2:45 PM - 4:15 PM"
                        },
                        new
                        {
                            CourseId = 52,
                            CourseCode = "AC401",
                            CourseName = "Senior Project I",
                            Credits = 3,
                            CurrentEnrollment = 39,
                            Description = "The third of the four-course project design series. In this intermediate course, students learn the importance of the voice of the customer, the customer/product market fit through using the business model canvas, and engineering design tools. Students learn and practice customer interview techniques and, through the feedback, help to develop appropriate solutions and prototypes. Students perform individual observations to discover unmet needs in industry and, after refining the needs, teams form to solve these needs. Comprehensively covers the student’s concentration in applied computing and its applications. Students work with faculty and external consultants and industry to refine their team based senior project. Prerequisite(s): AC 301 and PHYS 213. Pre- or corequisite(s): PHIL 354.",
                            MaxCapacity = 75,
                            Professor = "Prof53",
                            Time = "F 1:45 PM - 4:15 PM"
                        },
                        new
                        {
                            CourseId = 53,
                            CourseCode = "AC402",
                            CourseName = "Senior Project II",
                            Credits = 3,
                            CurrentEnrollment = 27,
                            Description = "Comprehensively covers the student’s concentration in applied computing and its applications. Students continue to work in their teams with faculty and external consultants and industry to refine and develop a final solution for their team based senior project. Prerequisite(s): AC 401.",
                            MaxCapacity = 75,
                            Professor = "Prof54",
                            Time = "F 1:45 PM - 4:15 PM"
                        },
                        new
                        {
                            CourseId = 54,
                            CourseCode = "AC461",
                            CourseName = "Digital Forensics",
                            Credits = 3,
                            CurrentEnrollment = 20,
                            Description = "Covers concepts related to hardware and software forensics, incident response, cyber crime and cyber law enforcement. Students learn different aspects of computer and cyber crime and ways to uncover, protect, exploit and document digital evidence. Students are exposed to different types of tools (both software and hardware), techniques and procedures, and are able to use them to perform rudimentary forensic investigations. Focuses on the entire life cycle of incident response including preparation, data collection, data analysis and remediation. Real world case studies reveal the methods behind and remediation strategies for today's most insidious attacks. Prerequisite(s): AC 326 .",
                            MaxCapacity = 30,
                            Professor = "Prof55",
                            Time = "M/W/F 9:30 AM - 11:15 AM"
                        },
                        new
                        {
                            CourseId = 55,
                            CourseCode = "AC462",
                            CourseName = "Cyber Physical Systems",
                            Credits = 4,
                            CurrentEnrollment = 15,
                            Description = "Focuses on trustworthy and resilient CPS, starting with NIST's CPS Framework. Students learn about common IoT infrastructures, integrate CPS into organizational risk management, and conduct cybersecurity risk assessments for critical cyber physical systems. Prerequisite(s): ENGR 220 and AC 326, or instructor’s consent.",
                            MaxCapacity = 35,
                            Professor = "Prof56",
                            Time = "M/W/F 11:15 AM - 12:45 PM"
                        },
                        new
                        {
                            CourseId = 56,
                            CourseCode = "AC463",
                            CourseName = "Cyber Risk Management",
                            Credits = 3,
                            CurrentEnrollment = 16,
                            Description = "This course covers application of risk and information security management to improve organizational resilience. Concepts include business impact analysis, incident response planning, disaster recovery planning, business continuity planning and security auditing. Prerequisite(s): AC 326.",
                            MaxCapacity = 35,
                            Professor = "Prof57",
                            Time = "M/W/F 10:45 AM - 12:45 PM"
                        },
                        new
                        {
                            CourseId = 57,
                            CourseCode = "AC464",
                            CourseName = "Web Application Security",
                            Credits = 3,
                            CurrentEnrollment = 21,
                            Description = "Develops an understanding of common web-based vulnerabilities and their impacts. Concepts include development and management of secure web-based systems, security mitigation strategies and penetration testing. Prerequisite(s): AC 324 and AC 326 .",
                            MaxCapacity = 35,
                            Professor = "Prof58",
                            Time = "M/W/F 11:15 AM - 12:45 PM"
                        },
                        new
                        {
                            CourseId = 58,
                            CourseCode = "ENGR220",
                            CourseName = "Applied Analog and Digital Electronics",
                            Credits = 3,
                            CurrentEnrollment = 14,
                            Description = "Provides a fundamental understanding of electronics and programming through content and active learning. Introduces basic electronic components and principles, sensors, actuators and electronic diagnostic tools. Builds confidence and creativity by designing, constructing and debugging circuits as well as programming a micro-controller to perform desired tasks. Introduces students to semiconductors and integrated circuits such as op-amps, combinational logic circuits and flip-flops. Students learn methods to interact with the physical world. At the end of the course, students should be comfortable developing simple electronic prototypes for future projects. Prerequisite(s): MATH 111.",
                            MaxCapacity = 35,
                            Professor = "Prof59",
                            Time = "T/TR 11:15 AM - 12:45 PM"
                        },
                        new
                        {
                            CourseId = 59,
                            CourseCode = "MATH511",
                            CourseName = "Linear Algebra",
                            Credits = 3,
                            CurrentEnrollment = 38,
                            Description = "An elementary study of linear algebra, including an examination of linear transformations and matrices over finite dimensional spaces. Prerequisite(s): MATH 243 with a grade point of 2.000 or better.",
                            MaxCapacity = 45,
                            Professor = "Prof60",
                            Time = "T/TR 12:30 PM - 1:45 PM"
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteCourseId")
                        .HasColumnType("int");

                    b.Property<int>("CoursePrerequisiteId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "PrerequisiteCourseId");

                    b.HasIndex("PrerequisiteCourseId");

                    b.ToTable("CoursePrerequisites");

                    b.HasData(
                        new
                        {
                            CourseId = 2,
                            PrerequisiteCourseId = 16,
                            CoursePrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 17,
                            PrerequisiteCourseId = 20,
                            CoursePrerequisiteId = 2
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.Degree", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegreeId"));

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DegreeId");

                    b.ToTable("Degrees");

                    b.HasData(
                        new
                        {
                            DegreeId = 1,
                            MajorName = "Computer Science"
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.DegreeRequirement", b =>
                {
                    b.Property<int>("DegreeRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegreeRequirementId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DegreeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SemesterSuggestion")
                        .HasColumnType("int");

                    b.HasKey("DegreeRequirementId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DegreeId");

                    b.ToTable("DegreeRequirements");

                    b.HasData(
                        new
                        {
                            DegreeRequirementId = 1,
                            CourseCode = "CS101",
                            CourseId = 1,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 1
                        },
                        new
                        {
                            DegreeRequirementId = 2,
                            CourseCode = "CS400",
                            CourseId = 3,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 2
                        },
                        new
                        {
                            DegreeRequirementId = 3,
                            CourseCode = "CS510",
                            CourseId = 4,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 3
                        },
                        new
                        {
                            DegreeRequirementId = 4,
                            CourseCode = "CS211",
                            CourseId = 23,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 4
                        },
                        new
                        {
                            DegreeRequirementId = 5,
                            CourseCode = "CS311",
                            CourseId = 25,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 5
                        },
                        new
                        {
                            DegreeRequirementId = 6,
                            CourseCode = "CS410",
                            CourseId = 27,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 6
                        },
                        new
                        {
                            DegreeRequirementId = 7,
                            CourseCode = "CS664",
                            CourseId = 28,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 7
                        },
                        new
                        {
                            DegreeRequirementId = 8,
                            CourseCode = "CS580",
                            CourseId = 29,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 8
                        },
                        new
                        {
                            DegreeRequirementId = 9,
                            CourseCode = "CS540",
                            CourseId = 30,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 9
                        },
                        new
                        {
                            DegreeRequirementId = 10,
                            CourseCode = "CS560",
                            CourseId = 31,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 10
                        },
                        new
                        {
                            DegreeRequirementId = 11,
                            CourseCode = "CS665",
                            CourseId = 32,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 11
                        },
                        new
                        {
                            DegreeRequirementId = 12,
                            CourseCode = "CS356",
                            CourseId = 33,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 12
                        },
                        new
                        {
                            DegreeRequirementId = 13,
                            CourseCode = "CS598",
                            CourseId = 34,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 13
                        },
                        new
                        {
                            DegreeRequirementId = 14,
                            CourseCode = "CS599",
                            CourseId = 35,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 15,
                            CourseCode = "MATH243",
                            CourseId = 2,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 16,
                            CourseCode = "MATH321",
                            CourseId = 5,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 17,
                            CourseCode = "MATH242",
                            CourseId = 16,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 18,
                            CourseCode = "PHIL125",
                            CourseId = 14,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 19,
                            CourseCode = "PHYS314",
                            CourseId = 17,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 20,
                            CourseCode = "PHYS316",
                            CourseId = 18,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 21,
                            CourseCode = "PHYS313",
                            CourseId = 20,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 22,
                            CourseCode = "PHIL354",
                            CourseId = 15,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 23,
                            CourseCode = "MATH322",
                            CourseId = 19,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 24,
                            CourseCode = "MATH511",
                            CourseId = 59,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 25,
                            CourseCode = "IME254",
                            CourseId = 21,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 26,
                            CourseCode = "ECE194",
                            CourseId = 22,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 27,
                            CourseCode = "ECE238",
                            CourseId = 24,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        },
                        new
                        {
                            DegreeRequirementId = 28,
                            CourseCode = "ECE394",
                            CourseId = 26,
                            DegreeId = 1,
                            IsRequired = true,
                            Major = "Computer Science",
                            SemesterSuggestion = 14
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "A",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 3,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "B+",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 4,
                            CourseId = 16,
                            EnrollmentDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "B+",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("DegreeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("DegreeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DegreeId = 1,
                            Email = "test@student.com",
                            FirstName = "Test Student",
                            LastName = "Onetest Student",
                            Major = "Computer Science",
                            Password = "test123",
                            Username = "Tstudent",
                            Year = "Sophomore"
                        });
                });

            modelBuilder.Entity("CourseScheduling.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentCourseId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("CourseScheduling.Models.Waitlist", b =>
                {
                    b.Property<int>("WaitlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaitlistId"));

                    b.Property<DateTime>("AddedToWaitlist")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("WaitlistId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Waitlists");
                });

            modelBuilder.Entity("CourseScheduling.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("CourseScheduling.Models.Course", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseScheduling.Models.Course", "PrerequisiteCourse")
                        .WithMany()
                        .HasForeignKey("PrerequisiteCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("CourseScheduling.Models.DegreeRequirement", b =>
                {
                    b.HasOne("CourseScheduling.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseScheduling.Models.Degree", "Degree")
                        .WithMany("Requirements")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("CourseScheduling.Models.Enrollment", b =>
                {
                    b.HasOne("CourseScheduling.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseScheduling.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseScheduling.Models.Student", b =>
                {
                    b.HasOne("CourseScheduling.Models.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("CourseScheduling.Models.StudentCourse", b =>
                {
                    b.HasOne("CourseScheduling.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseScheduling.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseScheduling.Models.Waitlist", b =>
                {
                    b.HasOne("CourseScheduling.Models.Course", "Course")
                        .WithMany("Waitlists")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseScheduling.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseScheduling.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Prerequisites");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("CourseScheduling.Models.Degree", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("CourseScheduling.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
